CREATE DATABASE DESGUACE;


INSERT INTO DATOS_COMUNES (
    NOMBRE,
    APELLIDO_A,
    APELLIDO_B,
    CONTRASENA,
    DIRECCION,
    CODIGO_POSTAL,
    CIUDAD,
    MUNICIPIO,
    TELEFONO,
    MOVIL,
    MAIL,
    DNI_CIF,
    FIREBASE_UID,
    RAZON_SOCIAL,
    NUMERO_CUENTA
) VALUES (
    'Juan',
    'Pérez',
    'Gómez',
    SHA2('contraseña_segura', 256), -- Aplicando SHA2 a la contraseña para generar el hash
    'Calle Falsa 123',
    28001,
    'Madrid',
    'Madrid',
    '912345678',
    '612345678',
    'juan.perez@mail.com',
    '12345678Z',
    'FR4igTSRuHTDIAxtRI9Xh08X1ZR2',
    NULL,
    'ES8300001111111111'  
);

CREATE TABLE CATEGORIAS_PIEZAS(
    ID_CATEGORIAS_PIEZAS INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100)
);

CREATE TABLE DATOS_COMUNES(
    ID_DATOS_COMUNES INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO_A VARCHAR(50),
    APELLIDO_B VARCHAR(50),
    CONTRASENA VARCHAR(255),
    DIRECCION VARCHAR(80),
    CODIGO_POSTAL INT,
    CIUDAD VARCHAR(50),
    MUNICIPIO VARCHAR(50),
    TELEFONO VARCHAR(9) UNIQUE,
    MOVIL VARCHAR(9) UNIQUE,
    MAIL VARCHAR(50) UNIQUE,
    DNI_CIF VARCHAR(9) UNIQUE,
    FIREBASE_UID VARCHAR(128) UNIQUE,
    RAZON_SOCIAL VARCHAR(80),
    NUMERO_CUENTA VARCHAR(30) UNIQUE
);

CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT AUTO_INCREMENT PRIMARY KEY,
    DATOS_COMUNES_FK INT NOT NULL,
    FOREIGN KEY (DATOS_COMUNES_FK) REFERENCES DATOS_COMUNES(ID_DATOS_COMUNES)
);

CREATE TABLE CLIENTE(
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, 
    DATOS_TARJETA VARCHAR(30) UNIQUE,
    DATOS_COMUNES_FK INT NOT NULL,
    FOREIGN KEY (DATOS_COMUNES_FK) REFERENCES DATOS_COMUNES(ID_DATOS_COMUNES)
);

CREATE TABLE EMPLEADOS(
    ID_EMPLEADOS INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_SS BIGINT UNIQUE NOT NULL,
    TIPO_CUENTA ENUM('ADM', 'GESTOR') NOT NULL,
    TOTAL_VACACIONES INT DEFAULT 30 CHECK (TOTAL_VACACIONES >= 0),
    DATOS_COMUNES_FK INT NOT NULL,
    FOREIGN KEY (DATOS_COMUNES_FK) REFERENCES DATOS_COMUNES(ID_DATOS_COMUNES)
);

CREATE TABLE NOMINAS(
    ID_NOMINAS INT AUTO_INCREMENT PRIMARY KEY,
    SUELDO_BRUTO DECIMAL(10,2) NOT NULL,
    ESTADO ENUM('PENDIENTE', 'PAGADA','BAJA') NOT NULL,
    MES DATE NOT NULL,
    EMPLEADOS_FK INT NOT NULL,
    FOREIGN KEY (EMPLEADOS_FK) REFERENCES EMPLEADOS(ID_EMPLEADOS)
);

CREATE TABLE FICHAJE(
    ID_FICHAJE INT AUTO_INCREMENT PRIMARY KEY,
    HORA_ENTRADA DATETIME,
    HORA_SALIDA DATETIME,
    EMPLEADOS_FK INT NOT NULL,
    FOREIGN KEY (EMPLEADOS_FK) REFERENCES EMPLEADOS(ID_EMPLEADOS)
);

CREATE TABLE VACACIONES (
    ID_VACACIONES INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    EMPLEADOS_FK INT NOT NULL,
    FOREIGN KEY (EMPLEADOS_FK) REFERENCES EMPLEADOS(ID_EMPLEADOS),
    CHECK (FECHA_FINAL >= FECHA_INICIO)
);

CREATE TABLE MARCAS(
    ID_MARCAS INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MARCA VARCHAR(50) NOT NULL
);

CREATE TABLE MODELO(
    ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MODELO VARCHAR(255),
    MARCA_MODELO_FK INT NOT NULL,
    FOREIGN KEY (MARCA_MODELO_FK) REFERENCES MARCAS(ID_MARCAS)
);

CREATE TABLE FACTURA(
    ID_FACTURAS INT AUTO_INCREMENT PRIMARY KEY,
    BASE DECIMAL(10,2) NOT NULL,
    IVA DECIMAL(10,2) NOT NULL,
    TIPO_PAGO VARCHAR(80) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE_FK INT NOT NULL,
    FOREIGN KEY (CLIENTE_FK) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PIEZAS(
    ID_PIEZAS INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(255),
    PESO DECIMAL(10,2),
    PRECIO_COMPRA DECIMAL(10,2),
    PRECIO DECIMAL(10,2),
    REFERENCIA VARCHAR(255),
    FECHA_YEAR VARCHAR(4),
    FECHA_INICIO_VENTA DATE,
    IMAGENES VARCHAR(510),
    CATEGORIAS_FK INT,
    VENDEDOR_FK INT NOT NULL, 
    EMPLEADO_FK INT,
    VENDIDO BOOLEAN,
    FOREIGN KEY (CATEGORIAS_FK) REFERENCES CATEGORIAS_PIEZAS(ID_CATEGORIAS_PIEZAS),
    FOREIGN KEY (VENDEDOR_FK) REFERENCES VENDEDOR(ID_VENDEDOR),
    FOREIGN KEY (EMPLEADO_FK) REFERENCES EMPLEADOS(ID_EMPLEADOS)
);

CREATE TABLE PIEZAS_MODELOS(
    ID_PIEZAS_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
    PIEZAS_FK INT NOT NULL,
    MODELO_FK INT NOT NULL,
    FOREIGN KEY (PIEZAS_FK) REFERENCES PIEZAS(ID_PIEZAS),
    FOREIGN KEY (MODELO_FK) REFERENCES MODELO(ID_MODELO)
);

CREATE TABLE LINEA_FACTURA(
    ID_LINEA_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    PIEZAS_FK INT NOT NULL,
    FACTURA_FK INT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PIEZAS_FK) REFERENCES PIEZAS(ID_PIEZAS),
    FOREIGN KEY (FACTURA_FK) REFERENCES FACTURA(ID_FACTURAS)
);

-- OBTENER NOMBRE COLUMNAS PIEZAS

DELIMITER //

CREATE PROCEDURE ObtenerNombresColumnasPiezas()
BEGIN
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
    AND (TABLE_NAME = 'PIEZAS' OR TABLE_NAME = 'CATEGORIAS_PIEZAS' OR TABLE_NAME = 'DATOS_COMUNES' OR TABLE_NAME = 'MODELO' OR TABLE_NAME = 'MARCAS')
    AND COLUMN_KEY NOT IN ('PRI', 'MUL')  -- Excluye claves primarias y foráneas
    AND COLUMN_NAME NOT IN ('FIREBASE_UID', 'CONTRASENA', 'DIRECCION', 'CODIGO_POSTAL', 'CIUDAD', 
    'MUNICIPIO', 'TELEFONO', 'MOVIL', 'MAIL', 'NUMERO_CUENTA', 'NOMBRE', 'APELLIDO_A', 'APELLIDO_B'); -- Excluir las columnas específicas
END //

DELIMITER ;

-- OBTENER NOMBRE COLUMNAS EMPLEADOS

DELIMITER //

CREATE PROCEDURE ObtenerNombresColumnasEmpleados()
BEGIN
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
    AND (TABLE_NAME = 'EMPLEADOS' OR TABLE_NAME = 'DATOS_COMUNES')
    AND COLUMN_KEY NOT IN ('PRI', 'MUL')  -- Excluye claves primarias y foráneas
    AND COLUMN_NAME NOT IN ('FIREBASE_UID', 'RAZON_SOCIAL'); -- Excluir las columnas específicas
END //

DELIMITER ;

-- OBTENER NOMBRE COLUMNAS VENDEDORES

DELIMITER //

CREATE PROCEDURE ObtenerNombresColumnasVendedores()
BEGIN
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
    AND (TABLE_NAME = 'VENDEDORES' OR TABLE_NAME = 'DATOS_COMUNES')
    AND COLUMN_KEY NOT IN ('PRI', 'MUL')  -- Excluye claves primarias y foráneas
    AND COLUMN_NAME NOT IN ('FIREBASE_UID', 'NOMBRE', 'APELLIDO_A', 'APELLIDO_B', 'CONTRASENA', 'NUMERO_SS'); -- Excluir las columnas específicas
END //

DELIMITER ;

-- OBTENER NOMBRE COLUMNAS MODELOS

DELIMITER //

CREATE PROCEDURE ObtenerNombresColumnasModelos()
BEGIN
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
    AND (TABLE_NAME = 'MODELO' OR TABLE_NAME = 'MARCAS')
    AND COLUMN_KEY NOT IN ('PRI', 'MUL');  -- Excluye claves primarias y foráneas
END //

DELIMITER ;

-- OBTENER NOMBRE COLUMNAS MARCAS

DELIMITER //

CREATE PROCEDURE ObtenerNombresColumnasMarcas()
BEGIN
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
    AND (TABLE_NAME = 'MARCAS')
    AND COLUMN_KEY NOT IN ('PRI', 'MUL');  -- Excluye claves primarias y foráneas
END //

DELIMITER ;


-- Insertar categorías de piezas de coches
INSERT INTO CATEGORIAS_PIEZAS (NOMBRE) VALUES 
('Motor'),
('Transmisión'),
('Frenos'),
('Suspensión'),
('Escape'),
('Sistema eléctrico'),
('Carrocería'),
('Interior');

-- Insertar marcas de coches
INSERT INTO MARCAS (NOMBRE_MARCA) VALUES 
('Toyota'),
('Ford'),
('Volkswagen'),
('BMW'),
('Mercedes-Benz'),
('Audi'),
('Honda'),
('Nissan');

-- Insertar modelos de coches (relacionados con las marcas)
INSERT INTO MODELO (NOMBRE_MODELO, MARCA_MODELO_FK) VALUES 
('Corolla', 1), -- Toyota
('Camry', 1), 
('Ranger', 2), -- Ford
('Mustang', 2),
('Golf', 3), -- Volkswagen
('Passat', 3),
('Serie 3', 4), -- BMW
('Serie 5', 4),
('Clase A', 5), -- Mercedes-Benz
('Clase C', 5),
('A3', 6), -- Audi
('A4', 6),
('Civic', 7), -- Honda
('Accord', 7),
('Altima', 8), -- Nissan
('Sentra', 8);
